import { StudentProfile, PortfolioProject, Internship, Application, MentorshipSession } from "../types/student.types"

// Initial Seed Profile for Alex Mensah with Employment Pathways
export const mockStudentProfile: StudentProfile = {
  id: "std-alex-mensah",
  name: "Alex Mensah",
  email: "student@catalyst.edu",
  phone: "+233 (0) 50 123 4567",
  location: "Accra, Ghana",
  programme: "MSc Information Technology",
  institution: "University of Science and Technology",
  level: "Postgraduate (Year 1)",
  graduationYear: "2026",
  bio: "Technical-focused ICT postgraduate student targeting Software Engineering roles. Proficient in web applications, database performance auditing, and system analysis.",
  readinessScore: 82, // Improved index calculation representation
  profileCompletion: 85,
  careerGoals: ["Software Engineer", "Database Administrator", "System Analyst"],
  preferredIndustries: ["Software Development", "Cloud Computing", "Networking", "Database Design"],
  certifications: ["AWS Certified Cloud Practitioner", "CCNA Security"],
  achievements: ["Winner of Annual Departmental Hackathon 2025", "Honor Roll List 2024-2025"],
  resumeUrl: "/uploads/alex-mensah-resume.pdf",

  // Employment enhancements
  careerStatus: "Seeking graduate employment",
  preferredJobTypes: ["Internship", "Graduate Program", "Full-Time Employment"],
  preferredWorkModes: ["Hybrid", "Remote"],
  preferredLocations: ["Accra", "Ghana", "International"],
  availabilityDate: "September 2026",
  allowEmployerDiscovery: true,

  // Skills
  skills: [
    { name: "React", level: 85, category: "Frontend" },
    { name: "Python", level: 70, category: "Backend" },
    { name: "SQL", level: 75, category: "Database" },
    { name: "Networking", level: 65, category: "Networking" },
    { name: "TypeScript", level: 60, category: "Frontend" },
  ],
}

// Initial Seed Projects
export const mockProjects: PortfolioProject[] = [
  {
    id: "proj-1",
    title: "Campus Attendance System",
    description: "A secure web portal developed using React and Node.js to coordinate academic term placements, including audit trackers.",
    techStack: ["Next.js", "PostgreSQL", "IoT"],
    status: "Completed",
    mentorReviewStatus: "Verified",
    githubUrl: "https://github.com/alexmensah/placement-manager",
    liveUrl: "https://placement-manager.demo.com",
  },
  {
    id: "proj-2",
    title: "Distributed Audit System",
    description: "A Python system monitoring network packet metadata anomalies and logging performance spikes inside database tables.",
    techStack: ["Python", "Networking", "PostgreSQL"],
    status: "Completed",
    mentorReviewStatus: "Pending",
    githubUrl: "https://github.com/alexmensah/audit-sys",
  },
]

// Initial Seed Opportunities (Opportunity Marketplace)
export const mockInternships: Internship[] = [
  {
    id: "job-1",
    company: "Hubtel Ghana",
    companyName: "Hubtel Ghana",
    title: "Software Engineering Intern",
    role: "Software Engineering Intern",
    location: "Accra, Ghana",
    type: "INTERNSHIP",
    workMode: "Hybrid",
    requiredSkills: ["React", "Node.js", "SQL"],
    deadline: "2026-08-15",
    experienceLevel: "Entry Level",
    description: "Work on Hubtel's merchant placement algorithms and transaction tracking APIs.",
    matchScore: 75,
    applicationStatus: "Interview",
    applied: true,
  },
  {
    id: "job-2",
    company: "Google Ghana",
    companyName: "Google Ghana",
    title: "Graduate Software Engineer",
    role: "Graduate Software Engineer",
    location: "Accra, Ghana",
    type: "GRADUATE_PROGRAM",
    workMode: "Hybrid",
    requiredSkills: ["Python", "Algorithms", "Go"],
    deadline: "2026-08-30",
    experienceLevel: "Graduate Level",
    description: "Join the Google EMEA software graduate development path working on regional API scale solutions.",
    matchScore: 82,
    applicationStatus: "Apply Now",
    applied: false,
  },
  {
    id: "job-3",
    company: "Stripe Tech",
    companyName: "Stripe Tech",
    title: "Junior Software Engineer",
    role: "Junior Software Engineer",
    location: "Accra, Ghana",
    type: "FULL_TIME",
    workMode: "Remote",
    requiredSkills: ["React", "TypeScript", "SQL"],
    deadline: "2026-09-01",
    experienceLevel: "Entry Level",
    description: "Integrate merchant checkout layouts and support SQL database schema updates.",
    matchScore: 87,
    applicationStatus: "Apply Now",
    applied: false,
  },
  {
    id: "job-4",
    company: "Google Cloud Labs",
    companyName: "Google Cloud Labs",
    title: "Cloud Infrastructure Support Specialist",
    role: "Cloud Infrastructure Support Specialist",
    location: "Remote",
    type: "CONTRACT",
    workMode: "Remote",
    requiredSkills: ["Linux", "AWS", "Python"],
    deadline: "2026-09-15",
    experienceLevel: "Junior Level",
    description: "A 6-month contract opportunity supporting cloud container orchestrations and server scripts.",
    matchScore: 78,
    applicationStatus: "Apply Now",
    applied: false,
  },
  {
    id: "job-5",
    company: "Google Cloud Labs",
    companyName: "Google Cloud Labs",
    title: "Cloud Infrastructure Intern",
    role: "Cloud Infrastructure Intern",
    location: "Remote",
    type: "INTERNSHIP",
    workMode: "Remote",
    requiredSkills: ["Python", "AWS", "Linux"],
    deadline: "2026-09-30",
    experienceLevel: "Entry Level",
    description: "Support our regional DevOps and system testing workflows under Google Cloud mentors.",
    matchScore: 81,
    applicationStatus: "Apply Now",
    applied: false,
  },
  {
    id: "job-6",
    company: "Hubtel Ghana",
    companyName: "Hubtel Ghana",
    title: "Junior Software Engineer",
    role: "Junior Software Engineer",
    location: "Accra, Ghana",
    type: "FULL_TIME",
    workMode: "Hybrid",
    requiredSkills: ["React", "Node.js", "SQL"],
    deadline: "2026-10-15",
    experienceLevel: "Entry Level",
    description: "Develop point-of-sale terminal logic and integrate billing schemas with database tables.",
    matchScore: 88,
    applicationStatus: "Applied",
    applied: true,
  },
]

// Initial Seed Applications
export const mockApplications: Application[] = [
  {
    id: "app-1",
    companyName: "Hubtel Ghana",
    role: "Software Engineering Intern",
    appliedDate: "2026-07-10",
    status: "Interview",
    opportunityType: "INTERNSHIP",
  },
  {
    id: "app-2",
    companyName: "Safaricom",
    role: "Database Administrator Associate",
    appliedDate: "2026-07-18",
    status: "Applied",
    opportunityType: "FULL_TIME",
  },
  {
    id: "app-3",
    companyName: "Hubtel Ghana",
    role: "Junior Software Engineer",
    appliedDate: "2026-07-22",
    status: "Applied",
    opportunityType: "FULL_TIME",
  },
]

// Initial Seed Mentorship
export const mockMentorSessions: MentorshipSession[] = [
  {
    id: "sess-1",
    mentorName: "Sarah Mentor",
    expertise: "Senior Engineering Manager",
    company: "Google EMEA",
    date: "2026-07-28",
    time: "2:00 PM GMT",
    status: "Scheduled",
    feedbackNotes: "Let's review your portfolio repository links and double check your database structure questions.",
  },
  {
    id: "sess-2",
    mentorName: "David Mentor",
    expertise: "Lead DevOps Specialist",
    company: "Hubtel Ghana",
    date: "2026-07-12",
    time: "10:30 AM GMT",
    status: "Completed",
    feedbackNotes: "Alex shows solid database auditing understanding. Advised him to package his python code into a clean Github repository.",
  },
]
export const mockMentorReviews = []
